title: Telereso KMP
description: Kotlin Multiplatform libraries projects
#remote_theme: just-the-docs/just-the-docs
theme: just-the-docs
#logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"
mermaid:
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"
heading_anchors: true
ga_tracking: G-V8S2X6JQZM

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

back_to_top: true
back_to_top_text: "Back to top"