# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Publish

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Gradle
      id: cache-gradle
      uses: actions/cache@v2
      with:
        path: |
         ~/.gradle/caches
         ~/.gradle/wrapper
        key: "gradle-cache"

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dry_run: "${{ github.ref != 'refs/heads/main' }}"

    - name: Setup Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v3

    - name: 'Authenticate to Google Cloud'
      if: github.ref == 'refs/heads/main'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_TELERESO }}'

      # Setup gcloud CLI
    - name: Set up Cloud SDK
      if: github.ref == 'refs/heads/main'
      uses: google-github-actions/setup-gcloud@v1
    - name: Restore public docs
      if: github.ref == 'refs/heads/main'
      run: |-
        bucket="gs://telereso-docs/docs"
        projectDocs="$bucket/projects/${{ github.repository_id }}/public/docs"
        mkdir -p public/docs
        gsutil -m -o "GSUtil:parallel_process_count=1" rsync -d -r "$projectDocs" public/docs

    - name: Build Artifacts
      run: |
        echo ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }} | base64 -d > secret_key
        bash scripts/publish.sh ${{ steps.tag_version.outputs.new_version }} "${{ github.ref == 'refs/heads/main' && '--sonatype' || '--local' }}"
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        SIGNING_SECRET_KEY_RING_FILE: "/Users/runner/work/kmp-core/kmp-core/secret_key"
        SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/.m2/
        retention-days: 2

    - name: Archive Docs
      uses: actions/upload-artifact@v2
      with:
        name: build-docs
        path: public
        retention-days: 1

    - name: Archive website
      uses: actions/upload-artifact@v2
      with:
        name: build-website
        path: website
        retention-days: 1

  website:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-docs
          path: build-docs

      - uses: actions/download-artifact@v2
        with:
          name: build-website
          path: website

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_TELERESO }}'
        # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Upload docs to bucket
        run: |-
          bucket="gs://telereso-docs/docs"
          projectDocs="$bucket/projects/${{ github.repository_id }}/public/docs"
          gsutil -m -o "GSUtil:parallel_process_count=1" rsync -r build-docs/docs "$projectDocs"

      - name: Build website
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./website
          destination: ./_website/

      - name: Move website and docs into public
        run: |-
          cp -R build-docs public
          cp -a _website/. public/

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'public'

  pages:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: website
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
